### ISSUE TITLE
cannot compile

### ISSUE THREAD

**Issue by sh4m2hwz** [vtil-project/VTIL-Python#7]
my previos steps:
```
cmake ..
```
```
> cmake --build . --config Release
MSBuild version 17.4.1+9a89d02ff for .NET Framework
  Checking File Globs
  capstone-static.vcxproj -> C:\Users\devirt\VTIL-Python\build\_deps\capstone-build\Release\capstone.lib
  keystone.vcxproj -> C:\Users\devirt\VTIL-Python\build\_deps\keystone-build\llvm\lib\Release\keystone.lib
  VTIL-Common.vcxproj -> C:\Users\devirt\VTIL-Python\build\external\core\VTIL-Common\Release\VTIL-Common.lib
  VTIL-SymEx.vcxproj -> C:\Users\devirt\VTIL-Python\build\external\core\VTIL-SymEx\Release\VTIL-SymEx.lib
  VTIL-Architecture.vcxproj -> C:\Users\devirt\VTIL-Python\build\external\core\VTIL-Architecture\Release\VTIL-Architect
  ure.lib
  VTIL-Compiler.vcxproj -> C:\Users\devirt\VTIL-Python\build\external\core\VTIL-Compiler\Release\VTIL-Compiler.lib
  module.cpp
C:\Users\devirt\VTIL-Python\external\pybind11\include\pybind11\cast.h(446,36): error C2027: использование неопределенно
го типа "_frame" [C:\Users\devirt\VTIL-Python\build\VTIL-Python.vcxproj]
C:\Users\devirt\AppData\Local\Programs\Python\Python311\include\pytypedefs.h(22,16): message : см. объявление "_frame"
[C:\Users\devirt\VTIL-Python\build\VTIL-Python.vcxproj]
C:\Users\devirt\VTIL-Python\external\pybind11\include\pybind11\cast.h(448,29): error C2027: использование неопределенно
го типа "_frame" [C:\Users\devirt\VTIL-Python\build\VTIL-Python.vcxproj]
C:\Users\devirt\AppData\Local\Programs\Python\Python311\include\pytypedefs.h(22,16): message : см. объявление "_frame"
[C:\Users\devirt\VTIL-Python\build\VTIL-Python.vcxproj]
C:\Users\devirt\VTIL-Python\external\pybind11\include\pybind11\cast.h(449,26): error C2027: использование неопределенно
го типа "_frame" [C:\Users\devirt\VTIL-Python\build\VTIL-Python.vcxproj]
C:\Users\devirt\AppData\Local\Programs\Python\Python311\include\pytypedefs.h(22,16): message : см. объявление "_frame"
[C:\Users\devirt\VTIL-Python\build\VTIL-Python.vcxproj]
C:/Users/devirt/VTIL-Python/external/pybind11/include\pybind11/pybind11.h(864,5): error C2059: синтаксическая ошибка: m
odule [C:\Users\devirt\VTIL-Python\build\VTIL-Python.vcxproj]
C:/Users/devirt/VTIL-Python/external/pybind11/include\pybind11/pybind11.h(864,71): error C2334: непредвиденные лексемы
перед "{"; пропуск вероятного тела функции [C:\Users\devirt\VTIL-Python\build\VTIL-Python.vcxproj]
C:/Users/devirt/VTIL-Python/external/pybind11/include\pybind11/pybind11.h(864,5): error C7586: Директива "module" должн
а заканчиваться символом ";" в той же строке. [C:\Users\devirt\VTIL-Python\build\VTIL-Python.vcxproj]
C:/Users/devirt/VTIL-Python/external/pybind11/include\pybind11/pybind11.h(2096,49): error C2039: "frame": не является ч
леном "_ts". [C:\Users\devirt\VTIL-Python\build\VTIL-Python.vcxproj]
C:\Users\devirt\AppData\Local\Programs\Python\Python311\include\cpython/pystate.h(82,8): message : см. объявление "_ts"
 [C:\Users\devirt\VTIL-Python\build\VTIL-Python.vcxproj]
C:/Users/devirt/VTIL-Python/external/pybind11/include\pybind11/pybind11.h(2097,8): error C2027: использование неопредел
енного типа "_frame" [C:\Users\devirt\VTIL-Python\build\VTIL-Python.vcxproj]
C:\Users\devirt\AppData\Local\Programs\Python\Python311\include\pytypedefs.h(22,16): message : см. объявление "_frame"
[C:\Users\devirt\VTIL-Python\build\VTIL-Python.vcxproj]
C:/Users/devirt/VTIL-Python/external/pybind11/include\pybind11/pybind11.h(2098,1): error C2027: использование неопредел
енного типа "_frame" [C:\Users\devirt\VTIL-Python\build\VTIL-Python.vcxproj]
C:\Users\devirt\AppData\Local\Programs\Python\Python311\include\pytypedefs.h(22,16): message : см. объявление "_frame"
[C:\Users\devirt\VTIL-Python\build\VTIL-Python.vcxproj]
C:/Users/devirt/VTIL-Python/external/pybind11/include\pybind11/pybind11.h(2101,18): error C2027: использование неопреде
ленного типа "_frame" [C:\Users\devirt\VTIL-Python\build\VTIL-Python.vcxproj]
C:\Users\devirt\AppData\Local\Programs\Python\Python311\include\pytypedefs.h(22,16): message : см. объявление "_frame"
[C:\Users\devirt\VTIL-Python\build\VTIL-Python.vcxproj]
C:/Users/devirt/VTIL-Python/external/pybind11/include\pybind11/pybind11.h(2101,30): error C2027: использование неопреде
ленного типа "_frame" [C:\Users\devirt\VTIL-Python\build\VTIL-Python.vcxproj]
C:\Users\devirt\AppData\Local\Programs\Python\Python311\include\pytypedefs.h(22,16): message : см. объявление "_frame"
[C:\Users\devirt\VTIL-Python\build\VTIL-Python.vcxproj]
C:/Users/devirt/VTIL-Python/external/pybind11/include\pybind11/pybind11.h(2100,33): error C2660: PyDict_GetItem: функци
я не принимает 1 аргументов [C:\Users\devirt\VTIL-Python\build\VTIL-Python.vcxproj]
C:\Users\devirt\AppData\Local\Programs\Python\Python311\include\dictobject.h(22,24): message : см. объявление "PyDict_G
etItem" [C:\Users\devirt\VTIL-Python\build\VTIL-Python.vcxproj]
C:/Users/devirt/VTIL-Python/external/pybind11/include\pybind11/pybind11.h(2100,33): message : при попытке сопоставить с
писок аргументов "()" [C:\Users\devirt\VTIL-Python\build\VTIL-Python.vcxproj]
C:\Users\devirt\VTIL-Python\src\module.cpp(83,20): error C2039: "def_submodule": не является членом "pybind11::module".
 [C:\Users\devirt\VTIL-Python\build\VTIL-Python.vcxproj]
C:/Users/devirt/VTIL-Python/external/pybind11/include\pybind11/pybind11.h(816,7): message : см. объявление "pybind11::m
odule" [C:\Users\devirt\VTIL-Python\build\VTIL-Python.vcxproj]
C:\Users\devirt\VTIL-Python\src\module.cpp(84,21): error C2039: "def_submodule": не является членом "pybind11::module".
 [C:\Users\devirt\VTIL-Python\build\VTIL-Python.vcxproj]
C:/Users/devirt/VTIL-Python/external/pybind11/include\pybind11/pybind11.h(816,7): message : см. объявление "pybind11::m
odule" [C:\Users\devirt\VTIL-Python\build\VTIL-Python.vcxproj]
C:\Users\devirt\VTIL-Python\src\module.cpp(85,20): error C2039: "def_submodule": не является членом "pybind11::module".
 [C:\Users\devirt\VTIL-Python\build\VTIL-Python.vcxproj]
C:/Users/devirt/VTIL-Python/external/pybind11/include\pybind11/pybind11.h(816,7): message : см. объявление "pybind11::m
odule" [C:\Users\devirt\VTIL-Python\build\VTIL-Python.vcxproj]
C:\Users\devirt\VTIL-Python\src\module.cpp(104,11): error C3536: debugger: не может использоваться до инициализации [C:
\Users\devirt\VTIL-Python\build\VTIL-Python.vcxproj]
C:\Users\devirt\VTIL-Python\src\module.cpp(104,11): error C2440: <function-style-cast>: невозможно преобразовать "initi
alizer list" в "vtil::python::debug_py" [C:\Users\devirt\VTIL-Python\build\VTIL-Python.vcxproj]
C:\Users\devirt\VTIL-Python\src\module.cpp(104,11): message : Ни один конструктор не смог принять исходный тип, либо ра
зрешение перегрузки конструктора неоднозначно [C:\Users\devirt\VTIL-Python\build\VTIL-Python.vcxproj]
C:\Users\devirt\VTIL-Python\src\module.cpp(111,14): error C3536: symbolic: не может использоваться до инициализации [C:
\Users\devirt\VTIL-Python\build\VTIL-Python.vcxproj]
C:\Users\devirt\VTIL-Python\src\module.cpp(111,14): error C2440: <function-style-cast>: невозможно преобразовать "initi
alizer list" в "vtil::python::variable_py" [C:\Users\devirt\VTIL-Python\build\VTIL-Python.vcxproj]
C:\Users\devirt\VTIL-Python\src\module.cpp(111,14): message : Ни один конструктор не смог принять исходный тип, либо ра
зрешение перегрузки конструктора неоднозначно [C:\Users\devirt\VTIL-Python\build\VTIL-Python.vcxproj]
C:\Users\devirt\VTIL-Python\src\module.cpp(127,20): error C3536: optimizer: не может использоваться до инициализации [C
:\Users\devirt\VTIL-Python\build\VTIL-Python.vcxproj]
C:\Users\devirt\VTIL-Python\src\module.cpp(127,20): error C2440: <function-style-cast>: невозможно преобразовать "initi
alizer list" в "vtil::python::pass_interface_py" [C:\Users\devirt\VTIL-Python\build\VTIL-Python.vcxproj]
C:\Users\devirt\VTIL-Python\src\module.cpp(127,20): message : Ни один конструктор не смог принять исходный тип, либо ра
зрешение перегрузки конструктора неоднозначно [C:\Users\devirt\VTIL-Python\build\VTIL-Python.vcxproj]
C:\Users\devirt\VTIL-Python\src\module.cpp(135,23): error C2440: <function-style-cast>: невозможно преобразовать "initi
alizer list" в "vtil::python::unique_identifier_py" [C:\Users\devirt\VTIL-Python\build\VTIL-Python.vcxproj]
C:\Users\devirt\VTIL-Python\src\module.cpp(135,23): message : Ни один конструктор не смог принять исходный тип, либо ра
зрешение перегрузки конструктора неоднозначно [C:\Users\devirt\VTIL-Python\build\VTIL-Python.vcxproj]
C:\Users\devirt\VTIL-Python\src\module.cpp(136,16): error C2440: <function-style-cast>: невозможно преобразовать "initi
alizer list" в "vtil::python::expression_py" [C:\Users\devirt\VTIL-Python\build\VTIL-Python.vcxproj]
C:\Users\devirt\VTIL-Python\src\module.cpp(136,16): message : Ни один конструктор не смог принять исходный тип, либо ра
зрешение перегрузки конструктора неоднозначно [C:\Users\devirt\VTIL-Python\build\VTIL-Python.vcxproj]
```
I'm using visual studio 2022

**Comment by Cod3Flow** [comment]
Got successful build on VS 2019 only using Python 3.5 and [this](https://github.com/pybind/pybind11/issues/2488#issuecomment-692481249) fix for pybind11.h.

Got successful build on VS 2019 using Python 3.11 after linking with new pybind11 (2.11.1 for now).
